[global]
   workgroup = WORKGROUP
   server string = Android Samba Server
   server role = standalone server
   obey pam restrictions = yes
   pam password change = yes
   map to guest = bad user
   usershare allow guests = yes

[PhoneStorage]
   path = /sdcard
   read only = no
   browsable = yes
   guest ok = yes
   force user = root
